### ISSUE TITLE
How many NDCG@5 score can the single model of this method achieve on the valid set ?

### ISSUE THREAD

**Issue by biandh** [steven95421/KDD_WinnieTheBest#1]
You are so good! I read the READM.md carefully, but I was still confused, mainly in the following aspects:

1. Can you give a simple example of the negative sample sampling method?

2. In this competition, 69 models have been trained based on Mcan and Visual Bert methods. Do these 69 models have any differences, such as parameters, training samples, etc?

3. Before post-processing, a single model based on Mcan or visual Bert is used to evalute the NDCG@5 on valid.tsv. How much can be achieved?

4. In the post-processing stage, the valid set is used to train the model. How to evaluate the model?

5. After post-processing, how many Score can a single model achieve in testA?

Looking forward to your reply ^_^

**Comment by steven95421** [comment]
Hi @biandh,
We have updated README.md with the answers.

**Comment by miziha-zp** [comment]
finding that you got magic improvement by finetuning in valid, and got  0.87-0.88 from single model(For VisualBERT, it was around 0.69. As for MCAN, it was around 0.7)....by the way, how did it improve by blending your 69 models?

**Comment by steven95421** [comment]
This huge performance boost is not from post-finetuning, but the post-processing part. We found out that the candidate products provided in the dataset have some bias. That is, if one item occurs in multiple candidate pools it is more likely this item is not the actual answer but just some bias.

**Comment by miziha-zp** [comment]
thx，amazing magic ！
