### ISSUE TITLE
great code ! only can you share data? to try your code?

### ISSUE THREAD

**Issue by Sandy4321** [steven95421/KDD_WinnieTheBest#2]
great code ! only can you share data? to try your code?

**Comment by steven95421** [comment]
You may need to download it from the competition site.
https://tianchi.aliyun.com/competition/entrance/231786/information

**Comment by FredHuang16** [comment]
> You may need to download it from the competition site.
> https://tianchi.aliyun.com/competition/entrance/231786/information

The download link failed. Can you share the training data?
