### ISSUE TITLE
extract the iamge feature

### ISSUE THREAD

**Issue by August-us** [steven95421/KDD_WinnieTheBest#3]
I want to use your model， But I could't fint more information of the MCAN. Can you give me some suggestion or give me your contact information. Second I want to ask that what good method for extracting the image features. I know some detection model, but I could't find a good pretrained model to extract the img. As I know, the class should be similar with the detection model, in order to extract suitable features.

could you help me? Thanks.

**Comment by August-us** [comment]
here is my email, August_us@163.com.  thanks for your reply.

**Comment by steven95421** [comment]
Hi @August-us,
You can know more details from their paper, here is the link:
https://openaccess.thecvf.com/content_CVPR_2019/html/Yu_Deep_Modular_Co-Attention_Networks_for_Visual_Question_Answering_CVPR_2019_paper.html
The competition organizer provides the image feature. But I think a Faster R-CNN would be strong enough to extract the image feature.

**Comment by August-us** [comment]
Thanks. However I want to use your method on my dataset. I got the model with FasterRCNN that could only detect the few categories. So I think it could get the poor performance.

**Comment by steven95421** [comment]
@August-us, Is your dataset unlabeled? I suggest you search for a similar open-source dataset with labels and label some data in your dataset.

**Comment by August-us** [comment]
> @August-us, Is your dataset unlabeled? I suggest you search for a similar open-source dataset with labels and label some data in your dataset.
tks
